[package]
name = "automagical"
version = "0.1.0"
authors = ["aspin"]
edition = "2018"

[dependencies]
amethyst = "0.15.0"

[features]
default = ["metal"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
