[package]
name = "automagical"
version = "0.1.0"
authors = ["aspin"]
edition = "2018"

[dependencies]
bevy = "0.1.2"

[features]
default = []

[profile.dev]
debug = 0

[build]
rustflags = ["-C link-arg=-fuse-ld=lld"]
