[package]
name = "automagical"
version = "0.1.0"
authors = ["aspin"]
edition = "2018"

[dependencies]
bevy = "0.3.0"
bevy_rapier3d = "0.6.0"
rand = "0.7.3"

[features]
default = []

[profile.dev]
debug = 0

[build]
rustflags = ["-C link-arg=-fuse-ld=lld"]
